services:
  db:
    image: postgres:latest
    ports:
      - '5435:5432'
    environment:
      - POSTGRES_USER=sekolah
      - POSTGRES_PASSWORD=jahat
      - POSTGRES_DB=mydb
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
